# Generated by Django 5.2.5 on 2025-08-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/excel/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('unique_values', models.TextField()),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='main_app.excelfile')),
            ],
        ),
        migrations.CreateModel(
            name='RowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField()),
                ('total_value', models.FloatField()),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='main_app.excelfile')),
            ],
        ),
    ]
